### ISSUE TITLE
Horizontal disabled scroll

### ISSUE THREAD

**Issue by MC42** [FRCScout/FRCScout#2]
Even at fully maximized, the scroll bars appear.

OS: Ubuntu Linux, 14.04 LTS.

![screenshot from 2016-07-26 21-22-48](https://cloud.githubusercontent.com/assets/6531081/17160954/2da5dcca-5377-11e6-9beb-b0e7c0958045.png)

**Comment by ErikBoesen** [comment]
Switching to a whole-page-scroll system to make this less annoying. I can't do anything to hide the scrollbars save hiding them globally, so that's just a client-side annoyance. This change should make it less annoying.
