### ISSUE TITLE
Default save folder and location for the folder

### ISSUE THREAD

**Issue by atf1999** [FRCScout/FRCScout#5]
As a suggestion, perhaps create a folder in the default home directory of the user called something like scouting-data.  This way, you know that you are saving to a valid location.  Also, have the ability for the user to change the saved directory for the json output file so that it is convenient for the user, as well toggle whether or not the user gets notified of the data being saved to the json file along with it's directory location.

**Comment by ErikBoesen** [comment]
Adding a textbox for changing path, with warning for invalid path. I think that should suffice.
