### ISSUE TITLE
NPM on windows <10

### ISSUE THREAD

**Issue by Twinters007** [FRCScout/FRCScout#7]
Without the bash for windows you can't just install npm with apt-get or cURL. Maybe included into the readme a link to download npm

**Comment by ErikBoesen** [comment]
![Image](http://i.imgur.com/FXCPc60.png)

**Comment by Twinters007** [comment]
That was a really well put together meme...A+

**Comment by ErikBoesen** [comment]
If you reopen this I will block you because you have no idea how long that took
